# Generated by Django 5.1.7 on 2025-05-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='expense_threshold',
            field=models.DecimalField(decimal_places=2, default=100000.0, help_text='Threshold for expense alerts in BDT', max_digits=10),
        ),
    ]
