# Generated by Django 5.1.7 on 2025-05-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='purchase_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
