# Generated by Django 5.1.7 on 2025-04-23 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='is_custom',
        ),
    ]
