# Generated by Django 5.1.7 on 2025-04-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='stripe_payment_intent_id',
        ),
        migrations.AlterField(
            model_name='package',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
