# Generated by Django 5.1.7 on 2025-04-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_payment_card_number_payment_cardholder_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
