# Generated by Django 5.1.7 on 2025-04-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_alter_payment_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
