# Generated by Django 5.1.7 on 2025-05-01 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0010_hotels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='is_available',
        ),
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('available_count', models.IntegerField(default=3)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='packages.hotels')),
            ],
            options={
                'unique_together': {('hotel', 'capacity')},
            },
        ),
    ]
