# Generated by Django 5.1.7 on 2025-05-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0013_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
