# Generated by Django 5.1.7 on 2025-05-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('expense_alert', 'Expense Alert'), ('package_confirmation', 'Package Confirmation'), ('new_package', 'New Package Arrival'), ('profile_update', 'Profile Update')], max_length=50),
        ),
    ]
